### ISSUE TITLE
Saved Query support in Workbench UI

### ISSUE THREAD

**Issue by fulghum** [dolthub/hosted-issues#111]
A Hosted Dolt customer thought Dolt's [saved query support](https://docs.dolthub.com/sql-reference/version-control/saved-queries) was really neat and wanted to use it, but couldn't find a way to add saved queries to a Hosted Dolt database. We do show the saved queries in the Workbench UI, but there isn't an easy way to add them through the UI. It would be cool if there was a button in the Workbench to "Save this query" or something similar. 

As a workaround, I thought we might be able to just manually insert into the `dolt_query_catalog` table, but since it doesn't exist yet, it seems like that likely won't work correctly even if we manually created it.

**Comment by tbantle22** [comment]
They should use views (which uses [`dolt_schemas`](https://docs.dolthub.com/sql-reference/version-control/dolt-system-tables#dolt_schemas)) to save their queries. There's a "Create View" button above the SQL Console.  When I was building the workbench we were talking about deprecating `dolt_query_catalog` since it's functionality is similar to `dolt_schemas`

**Comment by fulghum** [comment]
Ah, that's a great suggestion. Thank you @tbantle22! I'll ask the customer to try using views.
